[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
trust_lock = "9cZWC3nMxmkQGYw7JGMeaeaUmmQ3bfByaoZwvmyadvGx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
